version: '3.8'
services:
  postgres:
    build:
      context: services/postgres
      dockerfile: Dockerfile.development
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=calendar
      - POSTGRES_DB=new_calendar
      - POSTGRES_PASSWORD=float123
    volumes:
      - "db-data:/var/lib/postgresql/data"


  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    environment:
      - PORT=8091
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/new_calendar
#      - JS_URL=http://localhost
    image: 'calendar'
    ports:
      - 8091:8091
    depends_on:
      - postgres

volumes:
  db-data: