version: '3.8'

services:
  app:
    build: .
    ports:
      - "${OUT_PORT}:8080"
    env_file:
      - .env
    environment:
      - OUT_PORT=${OUT_PORT}
      - PROFILE=${PROFILE}
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: