ALTER TABLE users
    ADD created TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ADD updated TIMESTAMP WITHOUT TIME ZONE;

ALTER TABLE users
    ALTER COLUMN created SET NOT NULL;

ALTER TABLE users
    ALTER COLUMN updated SET NOT NULL;