CREATE TABLE event_group
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_event_group PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login    VARCHAR(255),
    password VARCHAR(255),
    fio      VARCHAR(255),
    email    VARCHAR(255),
    age      INTEGER,
    status   BOOLEAN,
    CONSTRAINT pk_users PRIMARY KEY (id)
);